name: 'dbt_warehouse_profiler'

version: '1.0.0'

config-version: 2

require-dbt-version: [">=1.10.0", "<3.0.0"]

profile: 'dbt_warehouse_profiler'

# Variables for customization
vars:
  dbt_warehouse_profiler:
    bigquery:
      # Default BigQuery region for cross-dataset queries
      default_region: 'us'

      # Schemas to exclude from validation by default
      exclude_schemas: []

      # Maximum number of preview rows to show in profile_table
      max_preview_rows: 10

    snowflake:
      # Schemas to exclude from validation by default
      exclude_schemas: []

      # Maximum number of preview rows to show in profile_table
      max_preview_rows: 10

# Dispatch configuration for cross-database compatibility
dispatch:
  - macro_namespace: dbt_warehouse_profiler
    search_order: ['dbt_warehouse_profiler', 'dbt']
flags:
  require_generic_test_arguments_property: true