version: 2

macros:
  - name: list_database_schemas
    description: |
      Lists all schemas (datasets) in your data warehouse project.
      Supports excluding specific schemas from the results.

  - name: list_tables
    description: |
      Lists all tables and views in a specific schema.
      Returns table names along with their types (BASE TABLE, VIEW, etc.)

  - name: list_columns
    description: |
      Lists all columns in a specific table with their data types and nullability.
      Results are ordered by the column's ordinal position in the table.

  - name: profile_table
    description: |
      Provides comprehensive profiling information about a table including:
      - Row count
      - Table size in bytes
      - Last modified timestamp
      - Preview of first N rows (configurable)
      - Partitioning status
      - Clustering status

  - name: profile_columns
    description: |
      Provides detailed column-level statistics for a table including:
      - Data type with precision
      - Null count and percentage
      - Distinct value count
      - Min/Max/Avg values (for numeric columns)
      - Min/Max values (for date/time columns)
      - True/False counts (for boolean columns)
      - Sample values (for string columns)

      Statistics vary by column type:
      - Numeric: nulls, distinct, min, max, avg
      - Date/Time: nulls, distinct, min, max
      - String: nulls, distinct, sample values
      - Boolean: nulls, distinct, true/false counts
      - Complex (ARRAY, STRUCT, JSON): nulls only

  - name: validate_source
    description: |
      Checks if a specific table is declared as a dbt source and has documentation.
      Returns the source name and documentation status if found.

  - name: validate_dataset_sources
    description: |
      Scans all tables in a dataset and validates their source declarations.
      Provides summary statistics showing the percentage of tables that are:
      - Declared as sources
      - Have documentation

  - name: execute_raw_query
    description: |
      Executes a raw SQL query against your data warehouse and displays the results.
      
      This macro allows you to run arbitrary SQL queries for ad-hoc analysis and exploration.
      The query is executed using your dbt profile connection, so all permissions and 
      credentials are inherited from your configured profile.
      
      **Output:**
      - Number of rows and columns returned
      - Column headers
      - All result rows (use LIMIT to control output size)
      
      **Security:**
      - Uses existing dbt profile credentials
      - Subject to warehouse permissions
      - No additional authentication required
      
      **Usage examples:**
      ```sql
      -- Simple SELECT query
      SELECT * FROM my_schema.my_table LIMIT 10
      
      -- Aggregation query
      SELECT status, COUNT(*) FROM orders GROUP BY status
      
      -- JOIN query
      SELECT u.name, o.total 
      FROM users u 
      JOIN orders o ON u.id = o.user_id 
      LIMIT 100
      ```
